@startuml
class Persona {
    - nombre: String
    - edad: int
    + Persona(nombre: String, edad: int)
    + getNombre(): String
    + getEdad(): int
}

class Estudiante {
    - matricula: String
    - universidad: Universidad
    + Estudiante(nombre: String, edad: int, matricula: String, universidad: Universidad)
    + getMatricula(): String
    + getUniversidad(): Universidad
}

class Universidad {
    - nombre: String
    + Universidad(nombre: String)
    + getNombre(): String
}

Persona <|-- Estudiante
Estudiante --> Universidad : pertenece a >
@enduml
